### ISSUE TITLE
binary Search Tree in Java

### ISSUE THREAD

**Issue by mahesh-11102** [De-Coder-01/DSA-Solutions#14]
`Question:` Write a Java program to identify the kth smallest element in the binary search tree ?

`my code Output: `

![image](https://user-images.githubusercontent.com/77436328/135504705-b4c48c35-2be8-4a65-9a69-db264fa26e41.png)

As a part of `Hacktoberfest` @De-Coder-01  please assign this issue to me

**Comment by De-Coder-01** [comment]
Done

**Comment by mahesh-11102** [comment]
Thank you @De-Coder-01  😄
